### ISSUE TITLE
Temperature conversion project

### ISSUE THREAD

**Issue by froumeli** [joeyajames/Python#120]
In this project, if the user inputs a text with alpabetic characters as the choice variable, it gives an error. Even if the choice is 1 or 2, if the user inputs a alphabetic string, it gives an error as well.  So, we need to check the user's answer and respond accordingly, so that it doesn't give an error.

**Comment by joeyajames** [comment]
@froumeli you are right, but this is a basic educational video. It is not intended to be robust production code. It's much easier for beginners to skip error checking and try/catch blocks when writing their first few lines of code. So I have no intention of changing this.

**Comment by froumeli** [comment]
Okay. Just in case, I was going to upload a project in your repo about
counting words in a text. However, in the code I check the user's answer.
Is it ok or should I change the code so it is easier for beginners to
understand?

Στις Τετ, 23 Μαρ 2022, 19:06 ο χρήστης Joe James ***@***.***>
έγραψε:
