### ISSUE TITLE
About the time complexity

### ISSUE THREAD

**Issue by bright1993ff66** [joeyajames/Python#5]
Thank you very much for your video and code!

But I actually have one question about your codes time complexity. The following two lines of codes showing that you are using Python slicing to construct the left half and right half:

`L = A[first:middle+1]`
`R = A[middle+1:last+1]`

Since the slicing operator is O(k), my question is does the time complexity of the merge sort still be O(nlogn) if we use the Python list slicing in our codes?

Thank you very much!

**Comment by joeyajames** [comment]
Any operation that is O(k) will not affect the time complexity of the algorithm because O(k) < O(n) < O(nlogn).
