### ISSUE TITLE
This repo doesn't have contributing file.

### ISSUE THREAD

**Issue by Varun270** [joeyajames/Python#96]
I am making one text file for contributing file for those who intend to contribute to this repository.

**Comment by Varun270** [comment]
@joeyajames  Please assign me this issue.

**Comment by joeyajames** [comment]
I'll probably set up an OOP folder in the Python repo to consolidate files to, but for now just put them in /Python

**Comment by Varun270** [comment]
@joeyajames  I have generated a pull request for this issue please do check it and let me know if you have any problem.

**Comment by Varun270** [comment]
@joeyajames  Since you have merged the pull request now can I close this issue.

**Comment by joeyajames** [comment]
done.
